// 단계 목록. tools/generate.js 가 만든 파일이라 손으로 고치지 않는다. 다시 만들려면 저장소 루트에서
//   node unblock/tools/generate.js --seed 2026 --climbs 24 --steps 1200 --per-tier 12
// 판은 36글자(6줄 × 6칸, 위 줄부터). '.' 빈칸, A 내 차, B~ 다른 차. moves 는 풀이기로 구한 최소 수다.
// id 는 판에서 나온 해시라 저장된 기록의 열쇠가 된다. 판이 같으면 목록을 다시 만들어도 기록이 이어진다.
// 모든 단계가 풀리고 최소 수가 맞는지는 test/unblock.test.js 가 확인한다.

export const LEVELS = [
  { id: 'h6s23m', tier: 'intro', moves: 2, board: 'B.....B...C.AA..C.DDEE..FFGGG.HHHII.' },
  { id: '12ayeir', tier: 'intro', moves: 2, board: '......BBBCCDEFGAADEFG....H.....HII..' },
  { id: '3es6e9', tier: 'intro', moves: 3, board: 'BC....BCD..EAAD..E.F.....FGG........' },
  { id: '1y71r0n', tier: 'intro', moves: 3, board: 'BC....BC.D.EAA.D.E......FF..........' },
  { id: '4huu0f', tier: 'intro', moves: 4, board: 'BB.......CDEAA.CDE..................' },
  { id: '1asxji9', tier: 'intro', moves: 4, board: '..BB.....C.DAA.C.D..EE..............' },
  { id: '20z45b', tier: 'intro', moves: 5, board: '..BB.....CDEAA.CDE........FF........' },
  { id: '81exfh', tier: 'intro', moves: 5, board: '.BBB....CCD.AA.ED....E.....F.....F..' },
  { id: '4i7pt0', tier: 'intro', moves: 6, board: '..BB....CDEFAACDEF...G.....G.....G..' },
  { id: '1k2fpid', tier: 'intro', moves: 6, board: '...BCC...BDE..AADE.....F.....F......' },
  { id: '2pospq', tier: 'intro', moves: 7, board: '..BCCC..BDD..AAE...FFE.....G.....G..' },
  { id: '3uujbz', tier: 'intro', moves: 7, board: '.....B..C..BAAC..B........DDEE..FFGG' },
  { id: 'q8h4or', tier: 'easy', moves: 8, board: 'BBB..C....DC..AADC...E....FE....FEGG' },
  { id: 'sfpjfz', tier: 'easy', moves: 8, board: '.....B..C..BAAC..B....DD..EEFF..GGHH' },
  { id: '3s63aj', tier: 'easy', moves: 9, board: 'BBB..C.DD..CAAE...F.E...FGGHHH......' },
  { id: '8d8uhr', tier: 'easy', moves: 9, board: '..B...C.B.DDCAA.E.....EFGGHHHF......' },
  { id: '8wzl46', tier: 'easy', moves: 10, board: 'B.CDEEB.CDFGBAAHFG...H.I...H.I.....I' },
  { id: 'adub44', tier: 'easy', moves: 10, board: '.BCCDE.BFGDEAAFG.E...H.....H.....HII' },
  { id: 'rf0t7', tier: 'easy', moves: 11, board: 'BBCCC.DE....DEAAF.DEGGF...HII...H...' },
  { id: '7f7jtz', tier: 'easy', moves: 11, board: 'BBB.CD.EEECD..FAAD..FG.....GHH...GII' },
  { id: '4m7nu9', tier: 'easy', moves: 12, board: '.BBB.......C..AA.CDDDE.C..FE....FEGG' },
  { id: '1yadgt8', tier: 'easy', moves: 12, board: '.BCCD..B.EDF.AAE.F..GHHH..G.....GII.' },
  { id: 'buay7z', tier: 'easy', moves: 13, board: '..BCCC..BDEF.AADEFGGGDHF....H.......' },
  { id: 'nk7saz', tier: 'easy', moves: 13, board: 'BBB.CD..E.CDAAE...F.....FGGHHH......' },
  { id: '1cvkb', tier: 'medium', moves: 14, board: 'BCDDEEBCFFGGAAHIJKLLHIJK....M..NN.M.' },
  { id: 'r0j1', tier: 'medium', moves: 15, board: 'BCCC.DB.EEFDAA.GFD.H.GII.HJJKK.LLMMM' },
  { id: '7zmbj', tier: 'medium', moves: 15, board: 'BBCCDEFGG.DEFHAADIFHJKKILLJM.....MNN' },
  { id: '6karm', tier: 'medium', moves: 16, board: 'BCC.D.BEE.DFAAG.DF..G.HHIII..JKKLL.J' },
  { id: '11a1n', tier: 'medium', moves: 17, board: 'BCCDEFB.GDEFAAGH.IJJKH.I..K...LLMM..' },
  { id: '3bthn', tier: 'medium', moves: 17, board: '.BCCDD.B..EFAA..EFGGHHHFIJJJKKILLLMM' },
  { id: '11qaa', tier: 'medium', moves: 18, board: 'BCCCDDBEEF.GAA.FHG.IJJHK.IL..KMMLNN.' },
  { id: '36dbm', tier: 'medium', moves: 18, board: 'BCDDE.BCF.EGAAF..G..HIIG..HJ..KKHJLL' },
  { id: '73nof', tier: 'medium', moves: 19, board: '..BCDD..BCEF.AA.EFGGHHHFI...JJIKKLLL' },
  { id: '70r4r', tier: 'medium', moves: 20, board: '.BCCDE.B.FDEAA.FGEHIIIG.H..J..H..JKK' },
  { id: '7ghah', tier: 'medium', moves: 20, board: 'BB.C..D..C.EDAACFEGGHHFIJ.KLLIJ.KMMM' },
  { id: 'wgu', tier: 'medium', moves: 21, board: '.BCCDD.BEFFGAAE.HGI..JHKILLJHK...MMK' },
  { id: 'pd76', tier: 'hard', moves: 22, board: 'BCCDD.B.EFG.AAEFG..HHII..JKKK..JLLL.' },
  { id: '8jlsq', tier: 'hard', moves: 23, board: '.BCCDE.BFGDEAAFG.E..HII...HJ....HJKK' },
  { id: 'ffnkr', tier: 'hard', moves: 23, board: 'BBCDDEF.CGGEF.AAHIJJ.KHI...KL.MMMKL.' },
  { id: '62j2l', tier: 'hard', moves: 24, board: 'B..CDDBEECF.AAGCFHIIG.JH.K..JL.KMMML' },
  { id: '2jmrg', tier: 'hard', moves: 25, board: 'BB.C..D..CEEDAAC.FGHIJJFGHI..KLLL..K' },
  { id: 'i80y7', tier: 'hard', moves: 26, board: 'BCCDEFBGHDEF.GHAAF..IJ....IJKK.LLLMM' },
  { id: '17ax6e', tier: 'hard', moves: 26, board: 'BBCCDEF.GGDEFAAH....IHJJKKIH.LMMMNNL' },
  { id: '1i1z7e', tier: 'hard', moves: 27, board: 'BBCC..D..EFFDAAEGH.IIIGHJJK..H..KLLL' },
  { id: 'c4rgi', tier: 'hard', moves: 28, board: 'BBCCCD.EEFFD.GAAHI.GJJHI..KLLLMMK...' },
  { id: 'eurbn', tier: 'hard', moves: 29, board: 'BCCDDDB..EFFBAAE..GH.IIJGH..KJLLMMKJ' },
  { id: 'vj7qr', tier: 'hard', moves: 29, board: '..BCCCDDBE..AAFE.G.HFIIGJHKK.GJLLMM.' },
  { id: 'orejt', tier: 'hard', moves: 30, board: 'BBC.D...CEDFAAGE.F..GHHFIJJK..ILLKMM' },
  { id: '6ogf4p', tier: 'expert', moves: 31, board: 'BCCDDEB..F.EAAGF..HHGIJJKKKIL..MMML.' },
  { id: '1hp53q', tier: 'expert', moves: 33, board: 'BCDDEEBC.FG.BAAFGHIIJ.GH..JKK..LLMM.' },
  { id: '1cikd2', tier: 'expert', moves: 34, board: 'BCCDEEBFFDG.BAAHG.IIJHGK..JLLK.MMNN.' },
  { id: 'y7q39', tier: 'expert', moves: 36, board: 'BBBCC...DEFFAADEGHI.JJGHIKK..LMMNNNL' },
  { id: 'h9hdj', tier: 'expert', moves: 38, board: 'BBBCD.EEECD.AA.CF.G.HHFIG.JKKILLJ...' },
  { id: '4iw3r3', tier: 'expert', moves: 40, board: '.BCCDD.B.EFFAA.EG.HIIIG.H.J.G.H.JKK.' },
  { id: '4zu6oh', tier: 'expert', moves: 41, board: 'BBCDD.EEC.FGHAA.FGHIIIFGH..JKKLL.J..' },
  { id: '95699c', tier: 'expert', moves: 43, board: 'BBCDD.E.C.F.EAA.FGEHHHFG...I..JJ.IKK' },
  { id: '8rsjcz', tier: 'expert', moves: 45, board: 'BBCDD.E.C.FGEAA.FGEHHHFG...IJJKK.ILL' },
  { id: 'crxdar', tier: 'expert', moves: 47, board: 'BBCDD.EEC.FGHAA.FGHIIIFGH..JKKLL.JMM' },
  { id: '1mkugi0', tier: 'expert', moves: 48, board: '..BCCCD.BE.FDAAE.FGGHIIF.JHKK..J....' },
  { id: '13n8zg4', tier: 'expert', moves: 50, board: '..BCCCD.BE.FDAAE.FGGHIIF.JHKK..JLL..' },
];
